# Generated by Django 3.2.11 on 2022-02-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("core", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="AdminPermissions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={
                "permissions": (
                    ("view_stats_page", "View stats page"),
                    ("invalidate_cloudflare", "Invalidate CloudFlare caches"),
                    ("trigger_tweets", "Trigger tweets"),
                ),
                "managed": False,
                "default_permissions": (),
            },
        ),
        migrations.AlterModelOptions(
            name="sitestat", options={"default_permissions": ()}
        ),
    ]
