# Generated by Django 3.2.15 on 2023-01-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_adminaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='status',
            field=models.CharField(choices=[('ONLINE', 'Online'), ('IN_REVIEW', 'In review'), ('REFUSED', 'Refused'), ('ESCALATED', 'Escalated')], default='IN_REVIEW', max_length=60),
        ),
    ]
