# Generated by Django 4.2.10 on 2024-02-19 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_pack_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(blank=True)),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TO_PROCESS", "To process"),
                            ("AGREED", "Agreed"),
                            ("DISAGREED", "Disagreed"),
                        ],
                        default="TO_PROCESS",
                        max_length=60,
                    ),
                ),
                (
                    "pack",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="core.pack"
                    ),
                ),
            ],
            options={
                "db_table": "reports",
            },
        ),
    ]
