# Generated by Django 4.2.10 on 2024-04-05 20:31

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_report"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ApiKey",
                    fields=[
                        (
                            "key",
                            models.UUIDField(
                                default=uuid.uuid4, primary_key=True, serialize=False
                            ),
                        ),
                        ("name", models.CharField(max_length=128)),
                    ],
                    options={
                        "db_table": "apikeys",
                    },
                ),
            ],
            database_operations=[],
        )
    ]
