# Generated by Django 4.2.10 on 2024-04-05 20:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_apikey"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="BotPreventionQuestion",
                    fields=[
                        (
                            "id",
                            models.AutoField(
                                auto_created=True,
                                primary_key=True,
                                serialize=False,
                                verbose_name="ID",
                            ),
                        ),
                        ("question", models.CharField(max_length=128)),
                        (
                            "answer",
                            models.CharField(
                                max_length=128,
                                validators=[
                                    django.core.validators.RegexValidator(
                                        message="The answer must be alphanumeric -- No special characters allowed.",
                                        regex="^[a-zA-Z0-9]+$",
                                    )
                                ],
                            ),
                        ),
                    ],
                    options={
                        "db_table": "botpreventionquestions",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
