# Generated by Django 4.2.10 on 2024-04-05 20:41

import uuid

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_botpreventionquestion"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="ContributionRequest",
                    fields=[
                        (
                            "id",
                            models.UUIDField(
                                default=uuid.uuid4,
                                editable=False,
                                primary_key=True,
                                serialize=False,
                            ),
                        ),
                        ("client_ip", models.GenericIPAddressField(protocol="IPv4")),
                        ("request_date", models.DateTimeField(auto_now_add=True)),
                        (
                            "question",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE,
                                to="core.botpreventionquestion",
                            ),
                        ),
                    ],
                    options={
                        "db_table": "contributionrequests",
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
