# Generated by Django 5.2.6 on 2025-09-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_contributionrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pack',
            name='tweeted',
        ),
    ]
