# Generated by Django 4.2.10 on 2025-09-08 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_remove_tweeted_field"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminpermissions",
            options={
                "default_permissions": (),
                "managed": False,
                "permissions": (
                    ("view_stats_page", "View stats page"),
                    ("invalidate_cloudflare", "Invalidate CloudFlare caches"),
                ),
            },
        ),
    ]
