# Generated by Django 4.2.10 on 2026-05-05 21:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_alter_adminpermissions_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACCEPT", "Accept"), ("REFUSE", "Refuse")],
                        default="REFUSE",
                        max_length=10,
                    ),
                ),
                ("review_comment", models.TextField(blank=True, default="")),
                ("tags_match", models.BooleanField(default=False)),
                ("nsfw", models.BooleanField(default=False)),
                (
                    "confidence",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("alert", models.BooleanField(default=True)),
                (
                    "pack",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_review",
                        to="core.pack",
                    ),
                ),
            ],
            options={
                "db_table": "ai_reviews",
            },
        ),
    ]
