# Generated by Django 3.1.4 on 2021-01-09 18:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contributionrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'apikeys',
            },
        ),
    ]
