# Generated by Django 3.1.6 on 2021-07-29 18:27

import uuid

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ApiKey",
            fields=[
                (
                    "key",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=128)),
            ],
            options={"db_table": "apikeys"},
        ),
        migrations.CreateModel(
            name="BotPreventionQuestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=128)),
                (
                    "answer",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="The answer must be alphanumeric -- No special characters allowed.",
                                regex="^[a-zA-Z0-9]+$",
                            )
                        ],
                    ),
                ),
            ],
            options={"db_table": "botpreventionquestions"},
        ),
        migrations.CreateModel(
            name="ContributionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("client_ip", models.GenericIPAddressField(protocol="IPv4")),
                ("request_date", models.DateTimeField(auto_now_add=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="api.botpreventionquestion",
                    ),
                ),
            ],
            options={"db_table": "contributionrequests"},
        ),
    ]
