# Generated by Django 4.2.10 on 2024-04-05 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ApiKey",
                ),
            ],
            database_operations=[],
        ),
    ]
