# Generated by Django 4.2.10 on 2024-04-05 20:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_botpreventionquestion"),
        ("api", "0002_delete_apikey"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterField(
                    model_name="contributionrequest",
                    name="question",
                    field=models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.botpreventionquestion",
                    ),
                ),
            ],
            database_operations=[],
        ),
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="BotPreventionQuestion",
                ),
            ],
            database_operations=[],
        ),
    ]
