# Generated by Django 4.2.10 on 2024-04-05 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_alter_contributionrequest_question_and_more"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name="ContributionRequest",
                ),
            ],
            database_operations=[],
        ),
    ]
