# Generated by Django 3.1.4 on 2021-01-03 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(max_length=32, unique=True)),
                ('pack_key', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('nsfw', models.BooleanField(default=False, verbose_name='NSFW')),
                ('original', models.BooleanField(default=False)),
                ('animated', models.BooleanField(default=False)),
                ('animated_detected', models.BooleanField(default=False)),
                ('animated_mode', models.CharField(choices=[('AUTO', 'Auto-detect'), ('FORCE_ANIMATED', 'Force animated'), ('FORCE_STILL', 'Force still')], default='AUTO', max_length=30)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('IN_REVIEW', 'In review'), ('REFUSED', 'Refused')], default='IN_REVIEW', max_length=60)),
                ('status_comments', models.TextField(blank=True)),
                ('submitter_comments', models.TextField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='packs', to='stickers.Tag')),
            ],
            options={
                'db_table': 'packs',
            },
        ),
    ]
