# Generated by Django 3.1.4 on 2021-01-03 22:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='pack_id',
            field=models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Pack id must be 32, lowercase and numbers.', regex='^[a-z0-9]{32}$')]),
        ),
        migrations.AlterField(
            model_name='pack',
            name='pack_key',
            field=models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='nomatch', message='Pack key must be 64, lowercase and numbers.', regex='^[a-z0-9]{64}$')]),
        ),
    ]
