# Generated by Django 3.1.6 on 2021-02-16 21:10

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pack_id', models.CharField(max_length=32, unique=True, validators=[django.core.validators.RegexValidator(code='nomatch', message='Pack id must be 32, lowercase and numbers.', regex='^[a-z0-9]{32}$')])),
                ('pack_key', models.CharField(max_length=64, validators=[django.core.validators.RegexValidator(code='nomatch', message='Pack key must be 64, lowercase and numbers.', regex='^[a-z0-9]{64}$')])),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=128)),
                ('id_cover', models.IntegerField(default=0)),
                ('source', models.CharField(blank=True, max_length=128)),
                ('nsfw', models.BooleanField(default=False, verbose_name='NSFW')),
                ('original', models.BooleanField(default=False)),
                ('animated', models.BooleanField(default=False)),
                ('animated_detected', models.BooleanField(default=False)),
                ('animated_mode', models.CharField(choices=[('AUTO', 'Auto-detect'), ('FORCE_ANIMATED', 'Force animated'), ('FORCE_STILL', 'Force still')], default='AUTO', max_length=30)),
                ('status', models.CharField(choices=[('ONLINE', 'Online'), ('IN_REVIEW', 'In review'), ('REFUSED', 'Refused')], default='IN_REVIEW', max_length=60)),
                ('status_comments', models.TextField(blank=True)),
                ('submitter_comments', models.TextField(blank=True)),
                ('tweeted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'packs',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
            options={
                'db_table': 'tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ShowcasedPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stickers.pack')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='pack',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='packs', to='stickers.Tag'),
        ),
    ]
