# Generated by Django 3.1.6 on 2021-06-21 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='editorschoice',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='ShowcasedPack',
        ),
    ]
