# Generated by Django 3.1.5 on 2021-01-13 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_auto_20210103_2216'),
    ]

    operations = [
        migrations.AddField(
            model_name='pack',
            name='tweeted',
            field=models.BooleanField(default=False),
        ),
    ]
