# Generated by Django 3.1.6 on 2021-06-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_auto_20210621_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='editorschoice',
            field=models.BooleanField(default=False, verbose_name="Editor's choice"),
        ),
    ]
