# Generated by Django 3.1.6 on 2021-06-22 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0003_auto_20210621_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pack',
            name='author',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='pack',
            name='source',
            field=models.CharField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='pack',
            name='title',
            field=models.CharField(max_length=256),
        ),
    ]
